module.exports={
  violin: {
    "A#3": "Samples/Violin/violin-aS3.wav",
    "A#4": "Samples/Violin/violin-aS4.wav",
    "A#5": "Samples/Violin/violin-aS5.wav",
    "A#6": "Samples/Violin/violin-aS6.wav",
    "C#4": "Samples/Violin/violin-cS4.wav",
    "C#5": "Samples/Violin/violin-cS5.wav",
    "C#6": "Samples/Violin/violin-cS6.wav",
    "C#7": "Samples/Violin/violin-cS7.wav",
    E4: "Samples/Violin/violin-e4.wav",
    E5: "Samples/Violin/violin-e5.wav",
    E6: "Samples/Violin/violin-e6.wav",
    G3: "Samples/Violin/violin-g3.wav",
    G4: "Samples/Violin/violin-g4.wav",
    G5: "Samples/Violin/violin-g5.wav",
    G6: "Samples/Violin/violin-g6.wav"
  },
  "string ensemble 1": {
    G3: "Samples/1st Violins/1st-violins-sus-g3.wav",
    "A#3": "Samples/1st Violins/1st-violins-sus-aS3.wav",
    "C#4": "Samples/1st Violins/1st-violins-sus-cS4.wav",
    E4: "Samples/1st Violins/1st-violins-sus-e4.wav",
    G4: "Samples/1st Violins/1st-violins-sus-g4.wav",
    "A#4": "Samples/1st Violins/1st-violins-sus-aS4.wav",
    "C#5": "Samples/1st Violins/1st-violins-sus-cS5.wav",
    E5: "Samples/1st Violins/1st-violins-sus-e5.wav",
    G5: "Samples/1st Violins/1st-violins-sus-g5.wav",
    "A#5": "Samples/1st Violins/1st-violins-sus-aS5.wav",
    "C#6": "Samples/1st Violins/1st-violins-sus-cS6.wav",
    E6: "Samples/1st Violins/1st-violins-sus-e6.wav",
    G6: "Samples/1st Violins/1st-violins-sus-g6.wav",
    "A#6": "Samples/1st Violins/1st-violins-sus-aS6.wav"
  },
  viola: {
    A3: "Samples/Violas/violas-sus-a3.wav",
    A4: "Samples/Violas/violas-sus-a4.wav",
    A5: "Samples/Violas/violas-sus-a5.wav",
    C3: "Samples/Violas/violas-sus-c3.wav",
    C4: "Samples/Violas/violas-sus-c4.wav",
    C6: "Samples/Violas/violas-sus-c6.wav",
    "D#3": "Samples/Violas/violas-sus-dS3.wav",
    "D#4": "Samples/Violas/violas-sus-dS4.wav",
    "F#3": "Samples/Violas/violas-sus-fS3.wav",
    "F#4": "Samples/Violas/violas-sus-fS4.wav",
    "F#5": "Samples/Violas/violas-sus-fS5.wav"
  },
  cello: {
    A2: "Samples/Celli/celli-sus-a2.wav",
    A3: "Samples/Celli/celli-sus-a3.wav",
    A4: "Samples/Celli/celli-sus-a4.wav",
    C2: "Samples/Celli/celli-sus-c2.wav",
    C3: "Samples/Celli/celli-sus-c3.wav",
    C4: "Samples/Celli/celli-sus-c4.wav",
    C5: "Samples/Celli/celli-sus-c5.wav",
    "D#2": "Samples/Celli/celli-sus-dS2.wav",
    "D#3": "Samples/Celli/celli-sus-dS3.wav",
    "D#4": "Samples/Celli/celli-sus-dS4.wav",
    "F#2": "Samples/Celli/celli-sus-fS2.wav",
    "F#3": "Samples/Celli/celli-sus-fS3.wav",
    "F#4": "Samples/Celli/celli-sus-fS4.wav"
  },
  contrabass: {
    A1: "Samples/Basses/basses-sus-a1.wav",
    A2: "Samples/Basses/basses-sus-a2.wav",
    A3: "Samples/Basses/basses-sus-a3.wav",
    C1: "Samples/Basses/basses-sus-c1.wav",
    C2: "Samples/Basses/basses-sus-c2.wav",
    C3: "Samples/Basses/basses-sus-c3.wav",
    C4: "Samples/Basses/basses-sus-c4.wav",
    "D#1": "Samples/Basses/basses-sus-dS1.wav",
    "D#2": "Samples/Basses/basses-sus-dS2.wav",
    "D#3": "Samples/Basses/basses-sus-dS3.wav",
    "F#1": "Samples/Basses/basses-sus-fS1.wav",
    "F#2": "Samples/Basses/basses-sus-fS2.wav",
    "F#3": "Samples/Basses/basses-sus-fS3.wav"
  }
};